version: '3.8'

services:
  php:
    build: .
    container_name: prelude-sdk-dev
    volumes:
      - .:/app
      - vendor:/app/vendor
    working_dir: /app
    environment:
      - COMPOSER_CACHE_DIR=/tmp/composer-cache
    command: tail -f /dev/null  # Keep container running
    
volumes:
  vendor:
    driver: local